import AosModule from "./modules/AosModule.js";
import MagnificModule from "./modules/MagnificModule.js";
import SwiperModule from "./modules/SwiperModule.js";
import MenuModule from "./modules/MenuModule.js";
import ScrollTopModule from "./modules/ScrollTopModule.js";
import ScrollToSectionModule from "./modules/ScrollToSectionModule.js";
import CountingModule from "./modules/CountingModule.js";
import CountDownDateModule from "./modules/CountDownDateModule.js";
import DatetimePickerModule from "./modules/DatetimePickerModule.js";
import LightGalleryModule from "./modules/LightGalleryModule.js";
import SlideToggleModule from "./modules/SlideToggleModule.js";
import tabModule from "./modules/tabModule.js";
import Select2Module from "./modules/Select2Module.js";
import HeaderModule from "./modules/HeaderModule.js";
import smoothScroll from "./modules/smoothScroll.js";
import TxtTrimModule from "./modules/TxtTrimModule.js";
import PopupModule from "./modules/PopupModule.js";
import { CheckDeviceModule } from "./modules/CheckDeviceModule.js";
import BannerGalleryModule from "./modules/BannerGalleryModule.js";
import AddClassModule from "./modules/AddClassModule.js";
import CategoryModule from "./modules/CategoryModule.js";
import ParticlesModule from "./modules/ParticlesModule.js";
import MagicScrollModule from "./modules/MagicScrollModule.js";
import ImgCompareModule from "./modules/ImgCompareModule.js";
import ScrollLaptopModule from "./modules/ScrollLaptopModule.js";
import RandomColorModule from "./modules/RandomColorModule.js";
import ChangeImgAniModule from "./modules/ChangeImgAniModule.js";
import LocomotiveModule from "./modules/LocomotiveModule.js";
import GsapModule from "./modules/GsapModule.js";
import ViewMoreModule from "./modules/ViewMoreModule.js";
import InputFormModule from "./modules/InputFormModule.js";
import DropDownModule from "./modules/DropDownModule.js";
import ChuanModule from "./modules/ChuanModule.js";
import ParallaxModule from "./modules/ParallaxModule.js";
import ScrollSectionModule from "./modules/ScrollSectionModule.js";
import CheckModule from "./modules/CheckModule.js";
import LetterModule from "./modules/LetterModule.js";
import SlideCustomModule from "./modules/SlideCustomModule.js";
import MegaMenuModule from "./modules/MegaMenuModule.js";
import HomeAnimationModule from "./modules/HomeAnimationModule.js";
import ImageSplitModule from "./modules/ImageSplitModule.js";
import ChooseProductImgModule from "./modules/ChooseProductImgModule.js";
import SnowModule from "./modules/SnowModule.js";
import SplideModule from "./modules/SplideModule.js";
import StoryModule from "./modules/StoryModule.js";
import MegaMenuHeaderModule from "./modules/MegaMenuHeaderModule.js";
import CanvasModule from "./modules/CanvasModule.js";
import Cloudhosting from "./modules/couldHost.js";
import Range from "./modules/Range.js";
import ScrollFilter from "./modules/ScrollFilter.js";

window.addEventListener("DOMContentLoaded", () => {
    // HeaderModule();
    // Cloudhosting();
    ScrollFilter();
    Range();
    LightGalleryModule();
    AosModule();
    MagnificModule();
    SwiperModule();
    MenuModule();
    ScrollTopModule();
    ScrollToSectionModule();
    CountingModule();
    CountDownDateModule();
    // DatetimePickerModule();
    SplideModule();

    SlideToggleModule();
    tabModule();
    Select2Module();
    smoothScroll();
    TxtTrimModule();

    PopupModule();
    CheckDeviceModule();

    BannerGalleryModule();
    AddClassModule();
    CategoryModule();
    ParticlesModule();
    MagicScrollModule();
    ImgCompareModule();
    ScrollLaptopModule();
    RandomColorModule();
    ChangeImgAniModule();
    LocomotiveModule();
    GsapModule();
    ViewMoreModule();
    InputFormModule();
    DropDownModule();
    ChuanModule();
    ParallaxModule();
    ScrollSectionModule();
    CheckModule();
    LetterModule();

    SlideCustomModule();
    MegaMenuModule();
    HomeAnimationModule();
    ImageSplitModule();
    ChooseProductImgModule();
    SnowModule();
    StoryModule();
    MegaMenuHeaderModule();
    CanvasModule();
    
});